// libs/core-extensions/react/src/lib/factories/feature-cell/feature.cell.adapter.ts
import { useSyncExternalStore } from 'react';
import {
  FeatureCellBaseShape,
  StateEmitSnapshotShape,
  StateSnapshotShape
} from '@sdux-vault/shared';
import { Observable } from 'rxjs';
import { FeatureCellShape as ReactFeatureCellShape } from '../../shapes/feature-cell.shape';

/**
 * Minimal core FeatureCell contract required by the React adapter.
 */
interface ReactAdapterCoreFeatureCellShape<T> extends FeatureCellBaseShape<T> {
  /**
   * Read-only synchronous snapshot of the current FeatureCell state.
   */
  state: StateSnapshotShape<T>;

  /**
   * Observable that emits committed state snapshots.
   */
  state$: Observable<StateEmitSnapshotShape<T>>;
}

/**
 * React adapter that augments a core FeatureCell with an explicit
 * `useSyncExternalStore()` render-time subscription method.
 *
 * This class preserves the core fluent API and snapshot access patterns while
 * exposing a React-native bridge for subscribing to state changes during render.
 */
export class ReactFeatureCellAdapter<T> {
  /**
   * Cached snapshot reference returned to React when the underlying state has
   * not materially changed.
   */
  #cachedSnapshot: StateSnapshotShape<T>;

  /**
   * Creates a new ReactFeatureCellAdapter for the provided core FeatureCell.
   *
   * @param core - The framework-agnostic FeatureCell instance to adapt.
   */
  constructor(private readonly core: ReactAdapterCoreFeatureCellShape<T>) {
    this.#cachedSnapshot = this.core.state;
  }

  /**
   * Builds and returns the React-augmented FeatureCell instance.
   *
   * @returns The FeatureCell with an attached `useSyncExternalStore()` method.
   */
  build(): ReactFeatureCellShape<T> {
    const cell = this.core;

    Object.defineProperty(cell, 'useSyncExternalStore', {
      configurable: true,
      enumerable: true,
      writable: false,
      value: () =>
        useSyncExternalStore(
          this.#subscribe.bind(this),
          this.#getSnapshot.bind(this),
          this.#getSnapshot.bind(this)
        )
    });

    return cell as unknown as ReactFeatureCellShape<T>;
  }

  /**
   * Returns a stable snapshot reference for React while preserving the core
   * cell's immutable public snapshot semantics.
   */
  #getSnapshot(): StateSnapshotShape<T> {
    const nextSnapshot = this.core.state;

    if (
      this.#cachedSnapshot.isLoading !== nextSnapshot.isLoading ||
      this.#cachedSnapshot.value !== nextSnapshot.value ||
      this.#cachedSnapshot.error !== nextSnapshot.error ||
      this.#cachedSnapshot.hasValue !== nextSnapshot.hasValue
    ) {
      this.#cachedSnapshot = nextSnapshot;
    }

    return this.#cachedSnapshot;
  }

  /**
   * Bridges FeatureCell state emissions into React's external store contract.
   */
  #subscribe(onStoreChange: () => void): () => void {
    const sub = this.core.state$.subscribe(() => {
      onStoreChange();
    });

    return () => sub.unsubscribe();
  }
}

// libs/core-extensions/angular/src/lib/providers/feature-cell/feature.cell.adapter.ts
import { computed, DestroyRef, inject, signal } from '@angular/core';
import {
  FeatureCellBaseShape,
  PipelineValue,
  StateEmitSnapshotShape,
  VaultErrorShape
} from '@sdux-vault/shared';
import { Subscription } from 'rxjs';
import { FeatureCellShape } from '../../shapes/feature-cell.shape';

/**
 * Angular adapter that augments a core FeatureCell with Angular Signal-based state access.
 *
 * This class bridges a framework-agnostic FeatureCellBaseShape into an Angular-friendly
 * representation by subscribing to state emissions and exposing derived, read-only
 * Angular Signals for value, loading state, error state, and value presence.
 */
export class AngularFeatureCellAdapter<T> {
  /**
   * Manages internal subscriptions to the core FeatureCell state stream.
   */
  readonly #subscriptions = new Subscription();

  /**
   * Signal representing the current pipeline value.
   */
  readonly #value = signal<PipelineValue<T>>(undefined);

  /**
   * Signal representing the current error state.
   */
  readonly #error = signal<VaultErrorShape | null>(null);

  /**
   * Signal representing whether the FeatureCell is currently loading.
   */
  readonly #isLoading = signal(false);

  /**
   * Computed signal indicating whether a non-null, non-undefined value is present.
   */
  readonly #hasValue = computed(() => {
    const value = this.#value();
    return value !== null && value !== undefined;
  });

  /**
   * Angular destroy reference used to coordinate lifecycle teardown.
   */
  readonly #destroyRef = inject(DestroyRef);

  /**
   * Creates a new AngularFeatureCellAdapter for the provided core FeatureCell.
   *
   * @param core - The framework-agnostic FeatureCell instance to adapt.
   */
  constructor(private readonly core: FeatureCellBaseShape<T>) {
    this.#subscriptions.add(
      this.core.state$.subscribe(
        (stateEmitSnapshot: StateEmitSnapshotShape<T>) => {
          this.#isLoading.set(stateEmitSnapshot?.snapshot?.isLoading ?? false);
          this.#error.set(stateEmitSnapshot?.snapshot?.error ?? null);
          this.#value.set(stateEmitSnapshot?.snapshot?.value ?? undefined);
        }
      )
    );

    this.#destroyRef.onDestroy(() => this.destroy());
  }

  /**
   * Builds and returns the Angular-augmented FeatureCell instance.
   *
   * @returns The FeatureCell with an attached Angular Signal-based state property.
   */
  build(): FeatureCellShape<T> {
    const cell = this.core as FeatureCellShape<T>;

    Object.defineProperty(cell, 'state', {
      configurable: true,
      enumerable: true,
      get: () => ({
        isLoading: this.#isLoading.asReadonly(),
        value: this.#value.asReadonly(),
        error: this.#error.asReadonly(),
        hasValue: this.#hasValue
      })
    });

    return cell;
  }

  /**
   * Destroys the adapter by tearing down subscriptions and delegating to the core FeatureCell.
   *
   * @returns void
   */
  destroy(): void {
    this.core.destroy();
    this.#subscriptions.unsubscribe();
  }
}
